# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6261352a71f0da5d6abe37d44270cebe929c9a620bf801362277bc1509cb1dfdb570c668a05c2d7319387eccadd1d45b1236088df42e2b81650f9d59af5cab0

test:
  secret_key_base: 58bd4af560a0777e33925f57a47012e71ac47959e0ab7a145f72cab1967d6d682fd699805b3ed5ed45b34fd1e72c088e9ff6f2151a6488b7d57f135f7882024f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
